### ISSUE TITLE
[BUG] de.uni_freiburg.informatik.ultimate.logic.SMTLIBException: Function field is already defined

### ISSUE THREAD

**Issue by mkotsbak** [arrow-kt/arrow-meta#1031]
Analyzis plugin gives this output:

```
exception during analysis: de.uni_freiburg.informatik.ultimate.logic.SMTLIBException
Function field is already defined.
de.uni_freiburg.informatik.ultimate.logic.SMTLIBException: Function field is already defined.
        at de.uni_freiburg.informatik.ultimate.logic.NoopScript.declareFun(NoopScript.java:263)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.declareFun(SMTInterpol.java:1377)
        at org.sosy_lab.java_smt.solvers.smtinterpol.SmtInterpolFormulaCreator.declareFun(SmtInterpolFormulaCreator.java:101)
        at org.sosy_lab.java_smt.solvers.smtinterpol.SmtInterpolFormulaCreator.makeVariable(SmtInterpolFormulaCreator.java:86)
        at org.sosy_lab.java_smt.solvers.smtinterpol.SmtInterpolFormulaCreator.makeVariable(SmtInterpolFormulaCreator.java:36)
        at org.sosy_lab.java_smt.solvers.smtinterpol.SmtInterpolIntegerFormulaManager.makeVariableImpl(SmtInterpolIntegerFormulaManager.java:55)
        at org.sosy_lab.java_smt.solvers.smtinterpol.SmtInterpolIntegerFormulaManager.makeVariableImpl(SmtInterpolIntegerFormulaManager.java:18)
        at org.sosy_lab.java_smt.basicimpl.AbstractNumeralFormulaManager.makeVariable(AbstractNumeralFormulaManager.java:175)
        at arrow.meta.plugins.analysis.smt.Solver$makeObjectVariable$1.invoke(Solver.kt:98)
        at arrow.meta.plugins.analysis.smt.Solver$makeObjectVariable$1.invoke(Solver.kt:98)
        at arrow.meta.plugins.analysis.smt.Solver.objects(Solver.kt:40)
        at arrow.meta.plugins.analysis.smt.Solver.makeObjectVariable(Solver.kt:98)
        at arrow.meta.plugins.analysis.phases.analysis.solver.search.ConstraintSearchKt.typeInvariants(ConstraintSearch.kt:91)
        at arrow.meta.plugins.analysis.phases.analysis.solver.check.ParametersKt$initialParameters$1$1$invariants$2.invoke(Parameters.kt:43)
        at arrow.meta.plugins.analysis.phases.analysis.solver.check.ParametersKt$initialParameters$1$1$invariants$2.invoke(Parameters.kt:43)
        at arrow.meta.plugins.analysis.phases.analysis.solver.check.ParametersKt.initialParameters(Parameters.kt:44)
        at arrow.meta.plugins.analysis.phases.analysis.solver.check.DeclarationsKt$checkTopLevel$1.invoke(Declarations.kt:112)
        at arrow.meta.plugins.analysis.phases.analysis.solver.check.DeclarationsKt$checkTopLevel$1.invoke(Declarations.kt:66)
        at arrow.meta.continuations.ContSeq$flatMap$1.invokeSuspend(ContSeq.kt:60)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at arrow.meta.continuations.ContSeqBuilder.hasNext(ContSeq.kt:233)
        at arrow.meta.continuations.ContSeq.drain(ContSeq.kt:297)
        at arrow.meta.plugins.analysis.phases.analysis.solver.check.EntryPointKt.checkDeclarationConstraints(EntryPoint.kt:126)
        at arrow.meta.plugins.analysis.phases.PhasesKt$analysisPhases$4.invoke(Phases.kt:136)
        at arrow.meta.plugins.analysis.phases.PhasesKt$analysisPhases$4.invoke(Phases.kt:129)
        at arrow.meta.dsl.config.ConfigSyntax$storageComponent$1.check(ConfigSyntax.kt:72)
        at arrow.meta.internal.registry.InternalRegistry$DelegatingContributor$registerModuleComponents$2.check(InternalRegistry.kt:651)
        at org.jetbrains.kotlin.resolve.ModifiersChecker$ModifiersCheckingProcedure.runDeclarationCheckers(ModifiersChecker.java:285)
        at org.jetbrains.kotlin.resolve.ModifiersChecker$ModifiersCheckingProcedure.checkModifierListCommon(ModifiersChecker.java:224)
        at org.jetbrains.kotlin.resolve.ModifiersChecker$ModifiersCheckingProcedure.checkModifiersForDeclaration(ModifiersChecker.java:183)
        at org.jetbrains.kotlin.resolve.DeclarationsChecker.process(DeclarationsChecker.kt:101)
        at org.jetbrains.kotlin.resolve.BodyResolver.resolveBodies(BodyResolver.java:255)
        at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations(LazyTopDownAnalyzer.kt:227)
        at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations$default(LazyTopDownAnalyzer.kt:58)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:127)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:96)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:262)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:53)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:113)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:253)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.repeatAnalysisIfNeeded(KotlinToJVMBytecodeCompiler.kt:223)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.repeatAnalysisIfNeeded(KotlinToJVMBytecodeCompiler.kt:223)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:100)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:58)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:170)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:434)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:120)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:357)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally$default(IncrementalCompilerRunner.kt:299)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl$rebuild(IncrementalCompilerRunner.kt:118)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:169)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:80)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:622)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:100)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1713)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**To Reproduce**

Caused by code:
```
private fun List<Tag>.findEnumField(tag: String, field: String): Field? =
    findTag(tag)?.getFieldsOrDefault(field, null)
        ?.let { Field(FieldType.String, it.displayName, it.enumValue.displayName) }
```
Maybe it is confused by overloaded function:

`Field` is a  data class:
`data class Field(val type: FieldType, val key: String, val value: String)`

**Expected behavior**
No exception during compiling.

**Environment (please complete the following information):**
 - Kotlin version: 1.6.10
- Arrow analyzis plugin version 2.0.2-SNAPSHOT

**Comment by mkotsbak** [comment]
Looks like the bug is fixed in latest snapshot version, thanks! :)
