### ISSUE TITLE
Memory leak IDE plugin

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow-meta#228]
IntelliJ printed this memory leak report about the Kotlin Meta IDE plugin.
Witnessed on latest master commit [e65a726](https://github.com/arrow-kt/arrow-meta/commit/e65a7269f1ebcd777b8ac0c9fb1e7fee18a202c3).

```
java.lang.RuntimeException: Memory leak detected: 'com.intellij.openapi.util.Disposer$2@2f0177c1' of class com.intellij.openapi.util.Disposer$2
See the cause for the corresponding Disposer.register() stacktrace:

        at com.intellij.openapi.util.objectTree.ObjectTree.assertIsEmpty(ObjectTree.java:236)
        at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:149)
        at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:145)
        at com.intellij.openapi.application.impl.ApplicationImpl.disposeSelf(ApplicationImpl.java:234)
        at com.intellij.openapi.application.impl.ApplicationImpl.doExit(ApplicationImpl.java:769)
        at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:744)
        at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:733)
        at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:729)
        at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:696)
        at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:691)
        at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeFrame$3.windowClosing(WelcomeFrame.java:111)
        at java.desktop/java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:357)
        at java.desktop/java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:357)
        at java.desktop/java.awt.Window.processWindowEvent(Window.java:2078)
        at java.desktop/javax.swing.JFrame.processWindowEvent(JFrame.java:298)
        at java.desktop/java.awt.Window.processEvent(Window.java:2037)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:817)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:405)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:404)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.Throwable
        at com.intellij.openapi.util.objectTree.ObjectNode.<init>(ObjectNode.java:54)
        at com.intellij.openapi.util.objectTree.ObjectTree.createNodeFor(ObjectTree.java:108)
        at com.intellij.openapi.util.objectTree.ObjectTree.register(ObjectTree.java:72)
        at com.intellij.openapi.util.Disposer.register(Disposer.java:92)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.doRegisterExtension(ExtensionPointImpl.java:131)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.registerExtension(ExtensionPointImpl.java:111)
        at arrow.meta.ide.internal.registry.IdeInternalRegistry$DefaultImpls.registerExtensionProvider(IdeInternalRegistry.kt:130)
        at arrow.meta.ide.IdeMetaPlugin.registerExtensionProvider(IdeMetaPlugin.kt:17)
        at arrow.meta.ide.internal.registry.IdeInternalRegistry$DefaultImpls.registerExtensionProvider$default(IdeInternalRegistry.kt:128)
        at arrow.meta.ide.internal.registry.IdeInternalRegistry$DefaultImpls.registerIdeExclusivePhase(IdeInternalRegistry.kt:59)
        at arrow.meta.ide.IdeMetaPlugin.registerIdeExclusivePhase(IdeMetaPlugin.kt:17)
        at arrow.meta.internal.registry.InternalRegistry$DefaultImpls.registerMetaComponents(InternalRegistry.kt:212)
        at arrow.meta.Meta$DefaultImpls.registerMetaComponents(Meta.kt)
        at arrow.meta.MetaPlugin.registerMetaComponents(MetaPlugin.kt:17)
        at arrow.meta.ide.MetaPluginRegistrarComponent.initComponent(MetaPluginRegistrarComponent.kt:24)
        at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:503)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:126)
        at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:262)
        at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:285)
        at com.intellij.openapi.project.impl.ProjectManagerImpl.access$300(ProjectManagerImpl.java:63)
        at com.intellij.openapi.project.impl.ProjectManagerImpl$2.run(ProjectManagerImpl.java:545)
        at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
        at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:447)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
        at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$9(ApplicationImpl.java:552)
        at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2019-11-24 12:24:23,072 [1805913]  ERROR - api.util.objectTree.ObjectTree - IntelliJ IDEA 2019.2.1  Build #IC-192.6262.58 
2019-11-24 12:24:23,072 [1805913]  ERROR - api.util.objectTree.ObjectTree - JDK: 11.0.3; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-11-24 12:24:23,072 [1805913]  ERROR - api.util.objectTree.ObjectTree - OS: Mac OS X 
2019-11-24 12:24:23,077 [1805918]  ERROR - api.util.objectTree.ObjectTree - Plugin to blame: Arrow version: 1.3.50-SNAPSHOT 

```

**Comment by i-walker** [comment]
We are aware of this issue. #62 aims to solve that
