### ISSUE TITLE
[IDEA Plugin] Error when opening a second project

### ISSUE THREAD

**Issue by rachelcarmena** [arrow-kt/arrow-meta#378]
### Error message

`Fatal error initializing plugin arrow-plugin`

### When

This error raises when trying the IDEA Plugin with `publishAndRunIde` and opening a second project. 

### Note

I'd like to try if it happens when having the plugin installed.

### Versions

```
ARROW_VERSION=0.10.4-SNAPSHOT
KOTLIN_VERSION=1.3.61
KOTLIN_IDEA_VERSION=1.3.61-release-IJ2019.3-1
INTELLIJ_IDEA_VERSION=2019.3.1
```

### Screenshot

![Screenshot from 2019-12-23 18-49-22](https://user-images.githubusercontent.com/22792183/71412472-16338080-264e-11ea-9e93-b088b73d1026.png)

### Call

```
at arrow.meta.ide.internal.registry.IdeInternalRegistry
$DefaultImpls.registerExtensionProvider(IdeInternalRegistry.kt:133)
```

<details>
  <summary>Full log</summary>
```WARN - roject.impl.ProjectManagerImpl - Fatal error initializing plugin arrow-plugin 
com.intellij.ide.plugins.StartupAbortedException: Fatal error initializing plugin arrow-plugin
        at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:55)
        at com.intellij.serviceContainer.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.kt:247)
        at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:50)
        at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
        at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:72)
        at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:65)
        at com.intellij.serviceContainer.PlatformComponentManagerImpl.createComponents(PlatformComponentManagerImpl.kt:177)
        at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:295)
        at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:315)
        at com.intellij.openapi.project.impl.ProjectManagerImpl.newProject(ProjectManagerImpl.java:216)
        at com.intellij.openapi.project.impl.ProjectManagerImpl.newProject(ProjectManagerImpl.java:183)
        at com.intellij.openapi.project.ex.ProjectManagerEx.createProject(ProjectManagerEx.java:117)
        at com.intellij.ide.util.projectWizard.ProjectBuilder.createProject(ProjectBuilder.java:76)
        at com.intellij.ide.impl.NewProjectUtil.doCreate(NewProjectUtil.java:121)
        at com.intellij.ide.impl.NewProjectUtil.createFromWizard(NewProjectUtil.java:76)
        at com.intellij.ide.impl.NewProjectUtil.createFromWizard(NewProjectUtil.java:71)
        at com.intellij.ide.actions.ImportModuleAction.doCreateFromWizard(ImportModuleAction.java:101)
        at com.intellij.ide.actions.ImportModuleAction.lambda$createFromWizard$0(ImportModuleAction.java:84)
        at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:83)
        at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:149)
        at com.intellij.ide.actions.ImportModuleAction.createFromWizard(ImportModuleAction.java:84)
        at com.intellij.ide.actions.ImportModuleAction.doImport(ImportModuleAction.java:78)
        at com.intellij.ide.actions.ImportProjectAction.actionPerformed(ImportProjectAction.java:30)
        at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:298)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:315)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:474)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:459)
        at com.intellij.ui.components.labels.ActionLink$1.linkSelected(ActionLink.java:45)
        at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:142)
        at com.intellij.ui.components.labels.ActionLink.doClick(ActionLink.java:54)
        at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:330)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6416)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
        at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:846)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:778)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: com.intellij.diagnostic.PluginException: This method should not be called on this object [Plugin: arrow-plugin]
        ... 67 more
Caused by: java.lang.UnsupportedOperationException: This method should not be called on this object
        at com.intellij.openapi.extensions.impl.UndefinedPluginDescriptor.getPluginId(UndefinedPluginDescriptor.java:15)
        at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.checkThatPointNotDuplicated(ExtensionsAreaImpl.java:213)
        at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.registerExtensionPoint(ExtensionsAreaImpl.java:218)
        at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.doRegisterExtensionPoint(ExtensionsAreaImpl.java:166)
        at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.registerExtensionPoint(ExtensionsAreaImpl.java:144)
        at arrow.meta.ide.internal.registry.IdeInternalRegistry$DefaultImpls.registerExtensionProvider(IdeInternalRegistry.kt:133)
        at arrow.meta.ide.IdeMetaPlugin.registerExtensionProvider(IdeMetaPlugin.kt:17)
        at arrow.meta.ide.internal.registry.IdeInternalRegistry$DefaultImpls.registerExtensionProvider$default(IdeInternalRegistry.kt:126)
        at arrow.meta.ide.internal.registry.IdeInternalRegistry$DefaultImpls.registerIdeExclusivePhase(IdeInternalRegistry.kt:58)
        at arrow.meta.ide.IdeMetaPlugin.registerIdeExclusivePhase(IdeMetaPlugin.kt:17)
        at arrow.meta.internal.registry.InternalRegistry$DefaultImpls.registerMetaComponents(InternalRegistry.kt:212)
        at arrow.meta.Meta$DefaultImpls.registerMetaComponents(Meta.kt)
        at arrow.meta.MetaPlugin.registerMetaComponents(MetaPlugin.kt:17)
        at arrow.meta.ide.MetaPluginRegistrarComponent.initComponent(MetaPluginRegistrarComponent.kt:24)
        at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:42)
        ... 64 more
```
</details>

**Comment by i-walker** [comment]
related to #227

**Comment by rachelcarmena** [comment]
It also happens when having the IDEA plugin installed. When closing a project and opening another one:

```
com.intellij.ide.plugins.StartupAbortedException: Fatal error initializing plugin io.arrow-kt.arrow
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:55)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.kt:247)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:50)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:72)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:65)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.createComponents(PlatformComponentManagerImpl.kt:177)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:295)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:315)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.convertAndLoadProject(ProjectManagerImpl.java:624)
	at com.intellij.platform.PlatformProjectOpenProcessor.prepareProject(PlatformProjectOpenProcessor.java:315)
	at com.intellij.platform.PlatformProjectOpenProcessor.lambda$openExistingProject$0(PlatformProjectOpenProcessor.java:241)
	at com.intellij.platform.ProjectUiFrameAllocator$run$1$1.run(ProjectFrameAllocator.kt:77)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:247)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$4(ApplicationImpl.java:441)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:209)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.intellij.diagnostic.PluginException: This method should not be called on this object [Plugin: io.arrow-kt.arrow]
	... 30 more
Caused by: java.lang.UnsupportedOperationException: This method should not be called on this object
	at com.intellij.openapi.extensions.impl.UndefinedPluginDescriptor.getPluginId(UndefinedPluginDescriptor.java:15)
	at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.checkThatPointNotDuplicated(ExtensionsAreaImpl.java:213)
	at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.registerExtensionPoint(ExtensionsAreaImpl.java:218)
	at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.doRegisterExtensionPoint(ExtensionsAreaImpl.java:166)
	at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.registerExtensionPoint(ExtensionsAreaImpl.java:144)
	at arrow.meta.ide.internal.registry.IdeInternalRegistry$DefaultImpls.registerExtensionProvider(IdeInternalRegistry.kt:133)
	at arrow.meta.ide.IdeMetaPlugin.registerExtensionProvider(IdeMetaPlugin.kt:17)
	at arrow.meta.ide.internal.registry.IdeInternalRegistry$DefaultImpls.registerExtensionProvider$default(IdeInternalRegistry.kt:126)
	at arrow.meta.ide.internal.registry.IdeInternalRegistry$DefaultImpls.registerIdeExclusivePhase(IdeInternalRegistry.kt:58)
	at arrow.meta.ide.IdeMetaPlugin.registerIdeExclusivePhase(IdeMetaPlugin.kt:17)
	at arrow.meta.internal.registry.InternalRegistry$DefaultImpls.registerMetaComponents(InternalRegistry.kt:212)
	at arrow.meta.Meta$DefaultImpls.registerMetaComponents(Meta.kt)
	at arrow.meta.MetaPlugin.registerMetaComponents(MetaPlugin.kt:17)
	at arrow.meta.ide.MetaPluginRegistrarComponent.initComponent(MetaPluginRegistrarComponent.kt:24)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:42)
	... 27 more
```
