### ISSUE TITLE
Ide publication

### ISSUE THREAD

**Issue by i-walker** [arrow-kt/arrow-meta#578]
installing the plugin locally results in multiple errors, regarding dependency resolution. 
```
java.lang.ExceptionInInitializerError
	at arrow.meta.ide.internal.IdeRegistrar.componentsInitialized(IdeRegistrar.kt:19)
	at com.intellij.idea.ApplicationLoader$callAppInitialized$2.run(ApplicationLoader.kt:705)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:193)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.intellij.diagnostic.PluginException: While loading class arrow.meta.ide.internal.registry.IdeInternalRegistry: arrow/meta/internal/registry/InternalRegistry [Plugin: io.arrow-kt.arrow]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:223)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:167)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:75)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:359)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:355)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:319)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:220)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:167)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:75)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at arrow.meta.ide.internal.IdeRegistrarKt.<clinit>(IdeRegistrar.kt:24)
	... 10 more
Caused by: java.lang.NoClassDefFoundError: arrow/meta/internal/registry/InternalRegistry
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:359)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:355)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:319)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:220)
	... 24 more
Caused by: java.lang.ClassNotFoundException: arrow.meta.internal.registry.InternalRegistry PluginClassLoader[io.arrow-kt.arrow, 1.3.61-SNAPSHOT] com.intellij.ide.plugins.cl.PluginClassLoader@7ff8767e
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:77)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 31 more 
```
Furthermore, the same issue resolves for plugin authors depending on Meta, [example branch](https://github.com/arrow-kt/arrow-meta-examples/pull/19).
<img width="460" alt="Screenshot 2020-04-23 at 08 38 12" src="https://user-images.githubusercontent.com/46971368/80070866-f81a5600-8543-11ea-93f1-5820ce9cf78c.png">

**Comment by rachelcarmena** [comment]
First issue is solved via #524 

Second issue (example) is a different issue which is not solved with IDEA plugin installation.
