### ISSUE TITLE
Silence script engine in Tests

### ISSUE THREAD

**Issue by i-walker** [arrow-kt/arrow-meta#654]
Please, checkout of this PR #652 to resolve this issue:

While running some UI tests in the Ide, enabling the script engine causes multiple errors, such as 

<details>
<summary>Failing Coercion tests</summary>
CoercionTest1 for 2 LM 
java.lang.AssertionError: CoercionTest1 for 2 LM 
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at arrow.meta.ide.testing.env.IdeTestInterpreterKt.interpreter(IdeTestInterpreter.kt:41)
	at arrow.meta.ide.testing.env.IdeTestInterpreterKt$runTest$1.invoke(IdeTestInterpreter.kt:21)
	at arrow.meta.ide.testing.env.IdeTestInterpreterKt$runTest$1.invoke(IdeTestInterpreter.kt)
	at arrow.meta.ide.testing.env.IdeTestInterpreterKt.runTest(IdeTestInterpreter.kt:23)
	at arrow.meta.ide.testing.env.IdeTestInterpreterKt.runTest$default(IdeTestInterpreter.kt:21)
	at arrow.meta.ide.testing.env.IdeTestInterpreterKt.ideTest(IdeTestInterpreter.kt:128)
	at arrow.meta.ide.plugins.proofs.markers.CoercionTest.test coercion line marker(CoercionTest.kt:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.intellij.testFramework.fixtures.LightPlatformCodeInsightFixture4TestCase$1.lambda$evaluate$0(LightPlatformCodeInsightFixture4TestCase.java:28)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:18)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:13)
	at com.intellij.testFramework.EdtTestUtilKt$runInEdtAndWait$3.run(EdtTestUtil.kt:67)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:416)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
</details>

The error above resolves by removing the `refinementAnnotator` in `ProofsIdePlugin.kt`
those are unrelated to the actual tests and tamper with the KotlinResolution in some cases. 

Is there a way to silence those errors without try catching them in Tests?

**Comment by i-walker** [comment]
resolved in #656
