### ISSUE TITLE
Failing gradle tests

### ISSUE THREAD

**Issue by i-walker** [arrow-kt/arrow-meta#693]
After refactoring the proof cache #692 the ide tests fail for the Given test in arrow/typeproofs repo.

<details>
<summary>gradle internal error</summary>
> Task :compileTestKotlin FAILED
e: java.lang.IllegalStateException: Symbol for @arrow.Given public val x: kotlin.String defined in test[DeserializedPropertyDescriptor@5edb4a09] is unbound
        at org.jetbrains.kotlin.ir.symbols.impl.IrBindableSymbolBase.getOwner(IrSymbolBase.kt:43)
        at arrow.meta.phases.codegen.ir.IrUtils.irCall(IrUtils.kt:54)
        at arrow.meta.plugins.proofs.phases.ir.ProofsIrCodegen.matchedCandidateProofCall(ProofsIrCodegen.kt:53)
        at arrow.meta.plugins.proofs.phases.ir.ProofsIrCodegen.substitutedProofCall(ProofsIrCodegen.kt:75)
        at arrow.meta.plugins.proofs.phases.ir.ProofsIrCodegen.givenProofCall(ProofsIrCodegen.kt:69)
        at arrow.meta.plugins.proofs.phases.ir.ProofsIrCodegen.insertGivenCall(ProofsIrCodegen.kt:226)
        at arrow.meta.plugins.proofs.phases.ir.ProofsIrCodegen.access$insertGivenCall(ProofsIrCodegen.kt:44)
        at arrow.meta.plugins.proofs.phases.ir.ProofsIrCodegen$proveCall$2.invoke(ProofsIrCodegen.kt:161)
        at arrow.meta.plugins.proofs.phases.ir.ProofsIrCodegen$proveCall$2.invoke(ProofsIrCodegen.kt:44)
        at arrow.meta.log.LogKt.invoke(Log.kt:13)
</details>

**Comment by rachelcarmena** [comment]
I think I found the root cause of this error when using the compiler context. I'm going to open a pull request on the `arrow-typeproofs` repository to relocate the source code to enable this test again.

**Comment by rachelcarmena** [comment]
I think I found the root cause of this error when using the compiler context. I'm going to open a pull request on the `arrow-typeproofs` repository to relocate the source code and to enable this test again.

**Comment by rachelcarmena** [comment]
https://github.com/arrow-kt/arrow-typeproofs/pull/6

**Comment by rachelcarmena** [comment]
Enabled again via #665 thanks to arrow-kt/arrow-typeproofs#6
